# Likes Report
## Madison Zellers
### 9/13/2024

Who or what is the source of your personal Instagram data?
The source of my data comes from my actions as a user and then gets recorded and stored

Why was this data created and what purposes can the data serve?
This data was created to help provide insights to that user's interest and make informed marketing decisions. The data makes your experience with an app highly personalized

In what ways may this data be unreliable?
The data may lead to  one having conclusions or assumptions about a person that is not true or at least not the full truth.

In [5]:
import json
import pandas as pd

In [6]:
path = "/Users/madisonzellers/emat-data/liked_posts.json"
with open(path) as j: 
    act = json.load(j)

In [7]:
act.keys()

dict_keys(['likes_media_likes'])

In [8]:
act_df = pd.DataFrame(act['likes_media_likes'])

In [156]:
act_df.head()

,title,string_list_data,timestamp
0,sabrinacarpenter,[{'href': 'https://www.instagram.com/p/C_Lx4b3...,1724847058
1,beigecardigan,[{'href': 'https://www.instagram.com/p/C_Baq9D...,1724781727
2,808_aidennspam,[{'href': 'https://www.instagram.com/p/C-gvMsP...,1724781499
3,playboy,[{'href': 'https://www.instagram.com/reel/C_Le...,1724781384
4,tumytum_,[{'href': 'https://www.instagram.com/reel/C-tK...,1724701214

In [157]:
act_df['string_list_data'].iloc [0] [0]

{'href': 'https://www.instagram.com/p/C_Lx4b3yF0Y/',
 'value': 'รฐ\x9f\x91\x8d',
 'timestamp': 1724847058}

In [158]:
act_df['string_list_data'].iloc [0] [0] ['timestamp']

1724847058

In [19]:
[x[0] ['timestamp']
if isinstance (x, list)
else '' for x  in act_df['string_list_data']]

[1724847058,
 1724781727,
 1724781499,
 1724781384,
 1724701214,
 1724701069,
 1724701003,
 1724700973,
 1724700954,
 1724700933,
 1724700915,
 1724700841,
 1724700813,
 1724700785,
 1724700744,
 1724700721,
 1724700570,
 1724698582,
 1724698568,
 1724698546,
 1724698528,
 1724698242,
 1724698197,
 1724596660,
 1724596641,
 1724596591,
 1724589912,
 1724589897,
 1724589895,
 1724589534,
 1724498554,
 1724498457,
 1724498424,
 1724498401,
 1724498389,
 1724498215,
 1724498184,
 1724439816,
 1724439758,
 1724439744,
 1724439718,
 1724439562,
 1724439513,
 1724439473,
 1724439434,
 1724439424,
 1724439373,
 1724439280,
 1724439268,
 1724439202,
 1724439173,
 1724439153,
 1724439126,
 1724439107,
 1724439078,
 1724438991,
 1724438969,
 1724438927,
 1724438882,
 1724438771,
 1724438731,
 1724438712,
 1724438670,
 1724438613,
 1724438566,
 1724438558,
 1724438486,
 1724438403,
 1724438388,
 1724438375,
 1724438333,
 1724438288,
 1724438271,
 1724438257,
 1724438251,
 1724438183,
 1724438151,
 1724438141,
 1724438130,
 1724438111,
 1724438098,
 1724438071,
 1724436316,
 1724436274,
 1724436264,
 1724436244,
 1724436231,
 1724436170,
 1724426005,
 1724425825,
 1724376244,
 1724376207,
 1724376181,
 1724376053,
 1724355429,
 1724355347,
 1724329269,
 1724329224,
 1724266706,
 1724266637,
 1724266633,
 1724266612,
 1724266535,
 1724266481,
 1724266425,
 1724266187,
 1724177565,
 1724177527,
 1724157409,
 1724157284,
 1724155122,
 1724110605,
 1724006027,
 1724005885,
 1723988347,
 1723896908,
 1723896713,
 1723829720,
 1723829689,
 1723829659,
 1723829603,
 1723829510,
 1723746900,
 1723746852,
 1723746815,
 1723746740,
 1723746656,
 1723746642,
 1723746557,
 1723746396,
 1723743500,
 1723681166,
 1723681116,
 1723681081,
 1723680996,
 1723680817,
 1723680674,
 1723680639,
 1723557268,
 1723557096,
 1723556961,
 1723556777,
 1723478318,
 1723478311,
 1723478278,
 1723478237,
 1723478229,
 1723478223,
 1723478182,
 1723478177,
 1723478007,
 1723400744,
 1723400520,
 1723340296,
 1723340288,
 1723340261,
 1723340224,
 1723340170,
 1723340162,
 1723340132,
 1723340116,
 1723340094,
 1723340035,
 1723340002,
 1723339960,
 1723339948,
 1723339893,
 1723339840,
 1723339647,
 1723339554,
 1723339518,
 1723339499,
 1723339466,
 1723339446,
 1723339437,
 1723339413,
 1723339376,
 1723339353,
 1723339322,
 1723339152,
 1723313878,
 1723253667,
 1723253631,
 1723253568,
 1723251636,
 1723251583,
 1723233101,
 1723233038,
 1723232990,
 1723232975,
 1723232948,
 1723232893,
 1723232882,
 1723232842,
 1723223904,
 1723223889,
 1723160047,
 1723160031,
 1723159993,
 1723159881,
 1723159866,
 1723159856,
 1723159824,
 1723159796,
 1723159560,
 1723078072,
 1723077998,
 1723077973,
 1723077932,
 1723077927,
 1723077914,
 1723077898,
 1723077744,
 1723058955,
 1723058910,
 1723058644,
 1722964060,
 1722964033,
 1722964013,
 1722964004,
 1722963961,
 1722955016,
 1722954846,
 1722951901,
 1722886227,
 1722886207,
 1722886194,
 1722886140,
 1722886098,
 1722886065,
 1722886048,
 1722885849,
 1722788322,
 1722781506,
 1722781384,
 1722710176,
 1722710168,
 1722710079,
 1722710029,
 1722709983,
 1722709958,
 1722709946,
 1722709930,
 1722709921,
 1722709850,
 1722709780,
 1722709627,
 1722709613,
 1722709601,
 1722709593,
 1722709576,
 1722709564,
 1722709557,
 1722709544,
 1722709531,
 1722709504,
 1722709493,
 1722709472,
 1722709464,
 1722709455,
 1722708983,
 1722708970,
 1722708963,
 1722708955,
 1722708849,
 1722708827,
 1722708800,
 1722708789,
 1722708640,
 1722700424,
 1722700191,
 1722623144,
 1722623060,
 1722623036,
 1722623012,
 1722622678,
 1722538817,
 1722538738,
 1722538728,
 1722538651,
 1722538542,
 1722525043,
 1722525033,
 1722525019,
 1722525011,
 1722524962,
 1722524946,
 1722524931,
 1722524709,
 1722447500,
 1722427678,
 1722427144,
 1722351615,
 1722343759,
 1722343292,
 1722274793,
 1722274588,
 1722273128,
 1722273084,
 1722273026,
 1722272965,
 1722256211,
 1722256033,
 1722186524,
 1722186083,
 1722186067,
 1722186016,
 1722185845,
 1722109204,
 1722109178,
 1722109168,
 1722109145,
 1722109142,
 1722083371,
 1722083350,
 1722083240,
 1722015513,
 1722015477,
 1722015395,
 1722015371,
 1722015261,
 1721992212,
 1721992128,
 1721970149,
 1721970129,
 1721907705,
 1721867128,
 1721867033,
 1721867028,
 1721867002,
 1721866976,
 1721866878,
 1721866860,
 1721866352,
 1721821069,
 1721821054,
 1721820750,
 1721737649,
 1721737558,
 1721737526,
 1721737511,
 1721737220,
 1721672219,
 1721672198,
 1721672179,
 1721672107,
 1721672086,
 1721649740,
 1721649733,
 1721649709,
 1721649676,
 1721649582,
 1721649481,
 1721649470,
 1721649450,
 1721649401,
 1721649354,
 1721649332,
 1721649184,
 1721587812,
 1721587702,
 1721564994,
 1721503216,
 1721503176,
 1721503136,
 1721503128,
 1721503087,
 1721503060,
 1721503039,
 1721503021,
 1721502954,
 1721480935,
 1721480918,
 1721480805,
 1721480789,
 1721480753,
 1721480738,
 1721480730,
 1721480670,
 1721480577,
 1721480534,
 1721480508,
 1721480492,
 1721480481,
 1721480465,
 1721480447,
 1721480163,
 1721423970,
 1721322072,
 1721321859,
 1721301841,
 1721298068,
 1721257131,
 1721175597,
 1721175577,
 1721175474,
 1721175177,
 1721080649,
 1721080591,
 1721080567,
 1721080548,
 1721080543,
 1721080524,
 1721080511,
 1721080500,
 1721080490,
 1721080464,
 1721080451,
 1721080443,
 1721080394,
 1721080380,
 1721080300,
 1721072972,
 1721072882,
 1720959551,
 1720959483,
 1720959445,
 1720959432,
 1720959385,
 1720959377,
 1720959313,
 1720959169,
 1720919544,
 1720886361,
 1720886327,
 1720886320,
 1720886310,
 1720886264,
 1720886236,
 1720886228,
 1720886186,
 1720886173,
 1720886156,
 1720886092,
 1720873615,
 1720873584,
 1720873518,
 1720873497,
 1720873455,
 1720873354,
 1720873326,
 1720873206,
 1720873062,
 1720808862,
 1720791933,
 1720791909,
 1720791892,
 1720791871,
 1720791856,
 1720791808,
 1720791730,
 1720791394,
 1720731764,
 1720731038,
 1720731019,
 1720730979,
 1720730900,
 1720730881,
 1720714195,
 1720714181,
 1720714173,
 1720714152,
 1720714112,
 1720714069,
 1720714052,
 1720713996,
 1720713971,
 1720713900,
 1720713828,
 1720713679,
 1720713592,
 1720713579,
 1720713092,
 1720712437,
 1720712408,
 1720712401,
 1720712373,
 1720646156,
 1720646108,
 1720646090,
 1720646062,
 1720645978,
 1720645965,
 1720645955,
 1720645945,
 1720645885,
 1720645859,
 1720645847,
 1720645839,
 1720645811,
 1720645800,
 1720645687,
 1720645664,
 1720645655,
 1720645642,
 1720645467,
 1720621531,
 1720621516,
 1720621465,
 1720621460,
 1720621448,
 1720621400,
 1720621377,
 1720542411,
 1720542390,
 1720542328,
 1720534159,
 1720534153,
 1720534118,
 1720534110,
 1720534081,
 1720534070,
 1720533739,
 1720532972,
 1720454491,
 1720454468,
 1720454431,
 1720454382,
 1720454345,
 1720454315,
 1720454278,
 1720454272,
 1720454264,
 1720454232,
 1720454228,
 1720454197,
 1720454147,
 1720454135,
 1720454117,
 1720454095,
 1720454090,
 1720454081,
 1720454067,
 1720454062,
 1720454037,
 1720453988,
 1720453963,
 1720453946,
 1720453936,
 1720453911,
 1720453905,
 1720453885,
 1720453873,
 1720453557,
 1720399622,
 1720399567,
 1720399560,
 1720399501,
 1720399484,
 1720399420,
 1720399395,
 1720399380,
 1720399283,
 1720399267,
 1720399220,
 1720399149,
 1720399114,
 1720370638,
 1720370631,
 1720309355,
 1720309239,
 1720283766,
 1720283690,
 1720227945,
 1720208528,
 1720208521,
 1720208440,
 1720208412,
 1720208408,
 1720208390,
 1720208382,
 1720208375,
 1720208344,
 1720208306,
 1720208294,
 1720208225,
 1720204714,
 1720134730,
 1720134640,
 1720127841,
 1720127599,
 1720014826,
 1720014814,
 1720014789,
 1720014725,
 1720014666,
 1720014480,
 1720014256,
 1719849301,
 1719849294,
 1719849261,
 1719849160,
 1719849115,
 1719849103,
 1719849049,
 1719848923,
 1719848900,
 1719848887,
 1719848722,
 1719776407,
 1719776249,
 1719776207,
 1719776088,
 1719767213,
 1719763941,
 1719711790,
 1719697134,
 1719697123,
 1719697090,
 1719697022,
 1719696974,
 1719696654,
 1719696538,
 1719696527,
 1719696518,
 1719696398,
 1719696330,
 1719696283,
 1719696260,
 1719696247,
 1719696236,
 1719696179,
 1719696164,
 1719696137,
 1719695983,
 1719601525,
 1719601349,
 1719601270,
 1719594801,
 1719590348,
 1719506636,
 1719506597,
 1719506571,
 1719506523,
 1719502294,
 1719448318,
 1719448308,
 1719448292,
 1719448145,
 1719420229,
 1719417339,
 1719362463,
 1719362196,
 1719172437,
 1719172417,
 1719172398,
 1719172375,
 1719172341,
 1719172316,
 1719172301,
 1719172290,
 1719172279,
 1719172153,
 1719172087,
 1719143020,
 1718984412,
 1718984403,
 1718984383,
 1718984374,
 1718984353,
 1718983848,
 1718908172,
 1718908153,
 1718887606,
 1718887598,
 1718887570,
 1718837719,
 1718837699,
 1718837668,
 1718837566,
 1718814606,
 1718814557,
 1718814553,
 1718814542,
 1718814530,
 1718755719,
 1718755680,
 1718755593,
 1718755566,
 1718755543,
 1718755530,
 1718755368,
 1718639576,
 1718588069,
 1718587959,
 1718587922,
 1718553111,
 1718553075,
 1718553066,
 1718552918,
 1718552906,
 1718552840,
 1718552817,
 1718552798,
 1718552335,
 1718482769,
 1718482648,
 1718482616,
 1718482556,
 1718482449,
 1718482358,
 1718482321,
 1718482317,
 1718482312,
 1718482254,
 1718482239,
 1718482194,
 1718482161,
 1718482071,
 1718482039,
 1718482026,
 1718482001,
 1718481972,
 1718481913,
 1718481910,
 1718481869,
 1718481852,
 1718481845,
 1718481825,
 1718481822,
 1718481763,
 1718481741,
 1718481731,
 1718481724,
 1718481686,
 1718481677,
 1718481620,
 1718481602,
 1718481571,
 1718481514,
 1718481478,
 1718481467,
 1718481451,
 1718481397,
 1718481367,
 1718481285,
 1718481204,
 1718481196,
 1718481181,
 1718408203,
 1718408190,
 1718408174,
 1718408157,
 1718408122,
 1718408113,
 1718408101,
 1718408089,
 1718406599,
 1718372864,
 1718372781,
 1718372772,
 1718372642,
 1718372590,
 1718372540,
 1718372509,
 1718372505,
 1718372490,
 1718372474,
 1718372422,
 1718372402,
 1718372379,
 1718293712,
 1718204781,
 1718195966,
 1718126193,
 1718126155,
 1718125741,
 1718125475,
 1718125261,
 1718125191,
 1718125054,
 1718124984,
 1718124854,
 1718118069,
 1718059412,
 1718049495,
 1718049406,
 1718049354,
 1718049029,
 1717947171,
 1717947087,
 1717946919,
 1717946597,
 1717937090,
 1717851371,
 1717851087,
 1717797678,
 1717797601,
 1717797541,
 1717797492,
 1717797391,
 1717796977,
 1717796955,
 1717796894,
 1717721057,
 1717720993,
 1717720944,
 1717720899,
 1717702805,
 1717702762,
 1717702739,
 1717702696,
 1717702672,
 1717702650,
 1717702630,
 1717702575,
 1717702543,
 1717702519,
 1717702438,
 1717702349,
 1717702325,
 1717702284,
 1717702266,
 1717702208,
 1717702205,
 1717700507,
 1717685885,
 1717529418,
 1717529305,
 1717529260,
 1717529255,
 1717529238,
 1717529219,
 1717529193,
 1717529158,
 1717529130,
 1717529082,
 1717529038,
 1717529015,
 1717528981,
 1717528915,
 1717528900,
 1717528885,
 1717528815,
 1717521649,
 1717506519,
 1717434716,
 1717431752,
 1717431659,
 1717350987,
 1717350745,
 1717350602,
 1717301278,
 1717301250,
 1717301226,
 1717301112,
 1717269997,
 1717269756,
 1717177094,
 1717177051,
 1717177033,
 1717176932,
 1717176916,
 1717176344,
 1717114538,
 1717114340,
 1717114258,
 1717114184,
 1717114170,
 1717114157,
 1717114109,
 1717114063,
 1717113764,
 1717078355,
 1717078312,
 1717078280,
 1717078249,
 1717078218,
 1717078178,
 1717077912,
 1716993462,
 1716921990,
 1716919237,
 1716919194,
 1716919137,
 1716918702,
 1716838832,
 1716838804,
 1716838742,
 1716838720,
 1716838691,
 1716838651,
 1716838585,
 1716838572,
 1716838563,
 1716838537,
 1716838484,
 1716769325,
 1716769101,
 1716769087,
 1716768968,
 1716768134,
 1716739555,
 1716739528,
 1716739391,
 1716739370,
 1716739346,
 1716739321,
 1716739297,
 1716739259,
 1716739225,
 1716739181,
 1716739152,
 1716739140,
 1716739111,
 1716739043,
 1716739017,
 1716738898,
 1716738757,
 1716738725,
 1716738706,
 1716738687,
 1716738625,
 1716738600,
 1716738592,
 1716738583,
 1716738551,
 1716738537,
 1716680960,
 1716680943,
 1716680933,
 1716680911,
 1716680889,
 1716680822,
 1716652211,
 1716652157,
 1716652048,
 1716652007,
 1716651935,
 1716651901,
 1716651802,
 1716651782,
 1716651748,
 1716651737,
 1716651719,
 1716651700,
 1716651691,
 1716651612,
 1716651578,
 1716651475,
 1716651430,
 1716648336,
 1716648326,
 1716648269,
 1716648019,
 1716561707,
 1716478944,
 1716478879,
 1716406561,
 1716406526,
 1716336655,
 1716336571,
 1716336564,
 1716336550,
 1716336539,
 1716336514,
 1716336509,
 1716336488,
 1716336482,
 1716314859,
 1716314853,
 1716314605,
 1716215590,
 1716215565,
 1716215522,
 1716215455,
 1716077524,
 1716077485,
 1716077383,
 1716077277,
 1716055990,
 1716055949,
 1715886271,
 1715886236,
 1715886222,
 1715886190,
 1715789578,
 1715723043,
 1715722982,
 1715722882,
 1715722843,
 1715722835,
 1715722729,
 1715722713,
 1715722664,
 1715722607,
 1715722589,
 1715722295,
 1715610472,
 1715533331,
 1715520066,
 1715473458,
 1715473414,
 1715473371,
 1715473286,
 1715473272,
 1715473265,
 1715473256,
 1715434819,
 1715434655,
 ...]

In [21]:
act_df['timestamp']=[x[0] ['timestamp'] for x in act_df['string_list_data']]

In [22]:
act_df.head()

,title,string_list_data,timestamp
0,sabrinacarpenter,[{'href': 'https://www.instagram.com/p/C_Lx4b3...,1724847058
1,beigecardigan,[{'href': 'https://www.instagram.com/p/C_Baq9D...,1724781727
2,808_aidennspam,[{'href': 'https://www.instagram.com/p/C-gvMsP...,1724781499
3,playboy,[{'href': 'https://www.instagram.com/reel/C_Le...,1724781384
4,tumytum_,[{'href': 'https://www.instagram.com/reel/C-tK...,1724701214

In [26]:
act_df1 = pd.DataFrame([x[0]for x in act_df['string_list_data']])

In [27]:
act_df1.head()

                                          href value   timestamp
0     https://www.instagram.com/p/C_Lx4b3yF0Y/  รฐยยย  1724847058
1     https://www.instagram.com/p/C_Baq9DRPHf/  รฐยยย  1724781727
2     https://www.instagram.com/p/C-gvMsPvF45/  รฐยยย  1724781499
3  https://www.instagram.com/reel/C_LeUyBuyNd/  รฐยยย  1724781384
4  https://www.instagram.com/reel/C-tKTKAydAu/  รฐยยย  1724701214

In [30]:
act_df1['title'] = act_df ['title']
act_df1.head()

,href,value,timestamp,title
0,https://www.instagram.com/p/C_Lx4b3yF0Y/,รฐยยย,1724847058,sabrinacarpenter
1,https://www.instagram.com/p/C_Baq9DRPHf/,รฐยยย,1724781727,beigecardigan
2,https://www.instagram.com/p/C-gvMsPvF45/,รฐยยย,1724781499,808_aidennspam
3,https://www.instagram.com/reel/C_LeUyBuyNd/,รฐยยย,1724781384,playboy
4,https://www.instagram.com/reel/C-tKTKAydAu/,รฐยยย,1724701214,tumytum_

In [32]:
act_df1.groupby('title').count()

                               href  value  timestamp
title
1.d.memes                         1      1          1
1223334444.4444333221             1      1          1
2.718281828459045235360287420    37     37         37
2000spophits                      1      1          1
2000stophits                      1      1          1
...                             ...    ...        ...
zieglergirlpets                   5      5          5
zigsnovaks                        1      1          1
zinia.lee                         1      1          1
zodiacobsession                   1      1          1
zro.nin                           2      2          2

[2250 rows x 3 columns]

In [33]:
act_df1.groupby('title').count().sort_values('value', ascending = False).head(10)

                 href  value  timestamp
title
jessiedumpster    853    853        853
jessiepaege       817    817        817
mattxiv           241    241        241
camimendes        198    198        198
colleen           173    173        173
ilovelucie0       131    131        131
itgoesthere       130    130        130
sweetcreaturep    108    108        108
drholly           105    105        105
sweetnspicegirl    96     96         96

Once I used the above cell to summarize the number of likes by account, the table seemed much more representative of what my Instagram page is more like. The first table that was made from the liked post file was not what I expected because some of the accounts I did not even recognize and did not remember liking their posts at all. Like for example why was playboy on there? Like that was quite embarassing for me to see. This made me reflect on the very top of the notebook where I answered the question in what ways may this data be unreliable and I answered it may lead other to make conclusions about a person that is not true and I think that case can definitely apply to my example. Also it made me think about all the other people including me that has had the same account since middle school. I have changed a lot as a person since middle school as I am sure we all have and to think that data that was taken from middle school can be used to make conclusions about someone as an adult seems scary.

My Hypothesis is if I mostly like posts on Instagram from influencers, then on Facebook I will follow local places. To test this I will use my who I followed file from Facebook. The reason I say that the type of accounts I interact with will be different between the two social media accounts is because both apps serve two different purposes for me. Otherwise why would I need both accounts. Also many influencers do not use Facebook, while many more of my family members use Facebook as opposed to instagram.

In [150]:
path = "/Users/madisonzellers/emat-data/who_you've_followed.json"
with open(path) as j: 
    met = json.load(j)

In [151]:
met.keys()

dict_keys(['following_v3'])

In [152]:
met['following_v3'][0]

{'name': 'The Ornament Shop', 'timestamp': 1685555555}

In [154]:
met_df = pd.DataFrame(met['following_v3'])

In [155]:
met_df.head(10)

                                   name   timestamp
0                     The Ornament Shop  1685555555
1        Kent State University at Stark  1665961904
2  Northwest High School Teen Institute  1600562907
3                Northwest Cheerleaders  1596309734
4               Northwest Local Schools  1592263137
5                        Northwest Band  1590331699
6                             Akron Zoo  1589919603
7                     Canal Fulton News  1587425113
8          Ron Koehler, Attorney at Law  1586700805
9                            Fox 8 News  1586118422

The data in this frame represents pages I have followed and the time of following and I believe the order is from most recently followed to earliest following. With tidy principles, the rows and the column names make sense, but the actually numerical values of the timestamps do not communicate a whole lot because it does show the time of following, but not in the usual way that humans communicate time. This data can be used to test my hypothesis, but I'm sure there is another data frame that could be made to make it more ideal to test the hypothesis with. In ways it is hard to compare Instagram and Facebook because on Facebook friends and followers are separate and the likes and reaction file on Facebook are not organized the same way that Instagram's likes are organized so it seemed nearly impossible for me to make a data frame from the facebook likes and reactions file. This dataframe does get insight to what accounts I am more interested in thogh and that is groups or places as opposed to Instagram which is more Influencers. With this table you could make the conclusion that on Instagram I follow more influencers and on Facebook I follow more businesses or places. You just would not be able to make specifc conclusions about how I interact with the pages I follow on Facebook vs the influencers I follow on Instagram.